# Form implementation generated from reading ui file 'D:\FinalProject\FinalProject\ui\login\login.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(933, 637)
        MainWindow.setMinimumSize(QtCore.QSize(933, 637))
        MainWindow.setMaximumSize(QtCore.QSize(933, 637))
        MainWindow.setStyleSheet("* {\n"
"    border: none;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #fff;\n"
"}\n"
"\n"
"#centralwidget {\n"
"\n"
"    background: url(\"D:/FinalProject/FinalProject/images/Welcome/login_bg.png\") no-repeat center center;\n"
"    background-size: cover;\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"#widget {\n"
"    background-color: rgb(243, 233, 206);\n"
"    border-radius: 20px;\n"
"}\n"
"QLineEdit {\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 0);\n"
"    padding: 5px 3px;\n"
"    border-radius: 5px;\n"
"}\n"
"#pushButtonRegister, #pushButtonLogin {\n"
"    background-color: rgb(124, 0, 11);\n"
"    padding: 10px 5px;\n"
"    border-radius: 5px;\n"
"}\n"
" #pushButtonTo_Register, #pushButtonTo_Login {\n"
"    background-color: transparent;\n"
"}\n"
"#frame, #frame_2, #frame_3, #frame_4, #frame_5 {\n"
"    background: none;\n"
"    border: none;\n"
"}\n"
"QLineEdit {\n"
"    border-radius: 10px;\n"
"    border: 2px solid #7c000b;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.widget = QtWidgets.QWidget(parent=self.frame_2)
        self.widget.setGeometry(QtCore.QRect(80, 190, 350, 400))
        self.widget.setMinimumSize(QtCore.QSize(350, 400))
        self.widget.setMaximumSize(QtCore.QSize(300, 400))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QCustomQStackedWidget(parent=self.widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.RegisterPage = QtWidgets.QWidget()
        self.RegisterPage.setObjectName("RegisterPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.RegisterPage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(parent=self.RegisterPage)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(9, 0, -1, -1)
        self.verticalLayout_3.setSpacing(9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(parent=self.frame_4)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\FinalProject\\FinalProject\\ui\\login\\../../images/icons/RedIcons/user_plus_ic.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_2.setStyleSheet("font: 87 18pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_3.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.lineEditUsername_Signup = QtWidgets.QLineEdit(parent=self.frame_3)
        self.lineEditUsername_Signup.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEditUsername_Signup.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lineEditUsername_Signup.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEditUsername_Signup.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditUsername_Signup.setObjectName("lineEditUsername_Signup")
        self.verticalLayout_3.addWidget(self.lineEditUsername_Signup)
        self.lineEditPassword_Signup = QtWidgets.QLineEdit(parent=self.frame_3)
        self.lineEditPassword_Signup.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEditPassword_Signup.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lineEditPassword_Signup.setText("")
        self.lineEditPassword_Signup.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditPassword_Signup.setObjectName("lineEditPassword_Signup")
        self.verticalLayout_3.addWidget(self.lineEditPassword_Signup)
        self.lineEditConfirmPassword_Signup = QtWidgets.QLineEdit(parent=self.frame_3)
        self.lineEditConfirmPassword_Signup.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEditConfirmPassword_Signup.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lineEditConfirmPassword_Signup.setText("")
        self.lineEditConfirmPassword_Signup.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditConfirmPassword_Signup.setObjectName("lineEditConfirmPassword_Signup")
        self.verticalLayout_3.addWidget(self.lineEditConfirmPassword_Signup)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(parent=self.RegisterPage)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setSpacing(9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButtonRegister = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButtonRegister.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButtonRegister.setMaximumSize(QtCore.QSize(130, 16777215))
        self.pushButtonRegister.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButtonRegister.setStyleSheet("font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(249, 246, 233);")
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.verticalLayout_5.addWidget(self.pushButtonRegister, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.pushButtonTo_Login = QtWidgets.QPushButton(parent=self.frame_5)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.pushButtonTo_Login.setFont(font)
        self.pushButtonTo_Login.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"color: rgb(0, 0, 0);")
        self.pushButtonTo_Login.setObjectName("pushButtonTo_Login")
        self.verticalLayout_5.addWidget(self.pushButtonTo_Login, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.RegisterPage)
        self.LoginPage = QtWidgets.QWidget()
        self.LoginPage.setObjectName("LoginPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.LoginPage)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_6 = QtWidgets.QFrame(parent=self.LoginPage)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_5.setMinimumSize(QtCore.QSize(50, 50))
        self.label_5.setMaximumSize(QtCore.QSize(50, 50))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\\FinalProject\\FinalProject\\ui\\login\\../images/icons/RedIcons/user_check_ic.svg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_6.setStyleSheet("font: 87 18pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_4.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.LoginPage)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_8.setSpacing(3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEditUsername_Login = QtWidgets.QLineEdit(parent=self.frame_7)
        self.lineEditUsername_Login.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEditUsername_Login.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEditUsername_Login.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditUsername_Login.setObjectName("lineEditUsername_Login")
        self.verticalLayout_8.addWidget(self.lineEditUsername_Login)
        self.lineEditPassword_Login = QtWidgets.QLineEdit(parent=self.frame_7)
        self.lineEditPassword_Login.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEditPassword_Login.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEditPassword_Login.setText("")
        self.lineEditPassword_Login.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditPassword_Login.setObjectName("lineEditPassword_Login")
        self.verticalLayout_8.addWidget(self.lineEditPassword_Login)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(parent=self.LoginPage)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.frame_9)
        self.checkBox_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBox_2.setStyleSheet("\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(0, 0, 0);")
        self.checkBox_2.setIconSize(QtCore.QSize(24, 24))
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox = QtWidgets.QCheckBox(parent=self.frame_9)
        self.checkBox.setStyleSheet("\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"color: rgb(0, 0, 0);")
        self.checkBox.setIconSize(QtCore.QSize(24, 24))
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_6.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(parent=self.LoginPage)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_9.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButtonLogin.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButtonLogin.setMaximumSize(QtCore.QSize(130, 16777215))
        self.pushButtonLogin.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButtonLogin.setStyleSheet("font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(249, 246, 233);")
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.verticalLayout_9.addWidget(self.pushButtonLogin, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.pushButtonTo_Register = QtWidgets.QPushButton(parent=self.frame_8)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.pushButtonTo_Register.setFont(font)
        self.pushButtonTo_Register.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"color: rgb(0, 0, 0);")
        self.pushButtonTo_Register.setObjectName("pushButtonTo_Register")
        self.verticalLayout_9.addWidget(self.pushButtonTo_Register, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_6.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(parent=self.LoginPage)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_7.setMaximumSize(QtCore.QSize(25, 25))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("D:\\FinalProject\\FinalProject\\ui\\login\\../images/icons/RedIcons/alert_circle_ic.svg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_6.addWidget(self.frame_10)
        self.stackedWidget.addWidget(self.LoginPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WelcomeCinex"))
        self.label_2.setText(_translate("MainWindow", "SIGN UP"))
        self.label_3.setText(_translate("MainWindow", "Enter your information below"))
        self.lineEditUsername_Signup.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lineEditPassword_Signup.setPlaceholderText(_translate("MainWindow", "Password"))
        self.lineEditConfirmPassword_Signup.setPlaceholderText(_translate("MainWindow", "Confirm Passord"))
        self.pushButtonRegister.setText(_translate("MainWindow", "Register"))
        self.pushButtonTo_Login.setText(_translate("MainWindow", "Already registered? Login"))
        self.label_6.setText(_translate("MainWindow", "LOG IN"))
        self.label_4.setText(_translate("MainWindow", "Enter your information below"))
        self.lineEditUsername_Login.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lineEditPassword_Login.setPlaceholderText(_translate("MainWindow", "Password"))
        self.checkBox_2.setText(_translate("MainWindow", "Admin"))
        self.checkBox.setText(_translate("MainWindow", "User"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Login"))
        self.pushButtonTo_Register.setText(_translate("MainWindow", "Not registered? Register"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>You cannot register an administrator account <br>because it is a privileged account.</p></body></html>"))
from Custom_Widgets.QCustomQStackedWidget import QCustomQStackedWidget
