# Form implementation generated from reading ui file 'D:\FinalProject\FinalProject\ui\admin\Export.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(458, 546)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Logo/images/Logo/Movie_logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 0);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setStyleSheet("background-color: rgb(124, 0, 11);\n"
"border: None")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_10 = QtWidgets.QWidget(parent=self.frame)
        self.widget_10.setStyleSheet("border: None")
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_9.setContentsMargins(12, -1, 12, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_9 = QtWidgets.QFrame(parent=self.widget_10)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_9.setStyleSheet("color: rgb(254, 254, 255);\n"
"font: 63 12pt \"Segoe UI Semibold\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_9.addWidget(self.frame_9)
        self.gridLayout_2.addWidget(self.widget_10, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.widget)
        self.calendarWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        self.widget_4 = QtWidgets.QWidget(parent=self.widget)
        self.widget_4.setStyleSheet("border: None")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_2.setStyleSheet("border: None")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(12, -1, 12, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_10.setStyleSheet("color: rgb(254, 254, 255);\n"
"font: 63 12pt \"Segoe UI Semibold\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.frame_3 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_8.addWidget(self.widget_2)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_5.setStyleSheet("border: None")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButtonExportExcel = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButtonExportExcel.setMinimumSize(QtCore.QSize(160, 30))
        self.pushButtonExportExcel.setMaximumSize(QtCore.QSize(160, 70))
        self.pushButtonExportExcel.setStyleSheet("border-radius: 8px;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 235, 192);\n"
"color: rgb(0, 0, 0);")
        self.pushButtonExportExcel.setObjectName("pushButtonExportExcel")
        self.verticalLayout_3.addWidget(self.pushButtonExportExcel)
        self.pushButtonExportCSV = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButtonExportCSV.setMinimumSize(QtCore.QSize(160, 30))
        self.pushButtonExportCSV.setMaximumSize(QtCore.QSize(160, 70))
        self.pushButtonExportCSV.setStyleSheet("border-radius: 8px;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 235, 192);\n"
"color: rgb(0, 0, 0);")
        self.pushButtonExportCSV.setObjectName("pushButtonExportCSV")
        self.verticalLayout_3.addWidget(self.pushButtonExportCSV)
        self.pushButtonExportJSON = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButtonExportJSON.setMinimumSize(QtCore.QSize(160, 30))
        self.pushButtonExportJSON.setMaximumSize(QtCore.QSize(160, 70))
        self.pushButtonExportJSON.setStyleSheet("border-radius: 8px;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 235, 192);\n"
"color: rgb(0, 0, 0);")
        self.pushButtonExportJSON.setObjectName("pushButtonExportJSON")
        self.verticalLayout_3.addWidget(self.pushButtonExportJSON)
        self.pushButtonExportTXT = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButtonExportTXT.setMinimumSize(QtCore.QSize(160, 30))
        self.pushButtonExportTXT.setMaximumSize(QtCore.QSize(160, 70))
        self.pushButtonExportTXT.setStyleSheet("border-radius: 8px;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"background-color: rgb(255, 235, 192);\n"
"color: rgb(0, 0, 0);")
        self.pushButtonExportTXT.setObjectName("pushButtonExportTXT")
        self.verticalLayout_3.addWidget(self.pushButtonExportTXT)
        self.verticalLayout_8.addWidget(self.widget_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addWidget(self.widget_4, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setStyleSheet("border: None")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_2 = QtWidgets.QFrame(parent=self.widget_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_9.setContentsMargins(30, 0, 30, 0)
        self.horizontalLayout_9.setSpacing(40)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.widget_3)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "User Information"))
        self.label_9.setText(_translate("Dialog", "Select the time period you need to export the file"))
        self.label_10.setText(_translate("Dialog", "Select the file format you want"))
        self.pushButtonExportExcel.setText(_translate("Dialog", "Excel File"))
        self.pushButtonExportCSV.setText(_translate("Dialog", "CSV File"))
        self.pushButtonExportJSON.setText(_translate("Dialog", "JSON File"))
        self.pushButtonExportTXT.setText(_translate("Dialog", "TXT File"))
