# Form implementation generated from reading ui file 'D:\FinalProject\FinalProject\ui\admin\Statistic.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(755, 561)
        Dialog.setMinimumSize(QtCore.QSize(755, 561))
        Dialog.setMaximumSize(QtCore.QSize(755, 583))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Logo/images/Logo/Movie_logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("QLabel {\n"
"font: 75 bold 12pt \"Arial\";\n"
"}\n"
"QLineEdit {\n"
"font: 12pt \"Microsoft YaHei UI\";\n"
"}\n"
"#centralwidget{\n"
"    background-color: #fdfdfa;\n"
"}\n"
"QTextEdit {\n"
"    border: 1px solid #7c000b;\n"
"    border-radius: 10px;\n"
"   padding: 5px;\n"
"}\n"
"QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 1.5px solid #7c000b; \n"
"    background: transparent; \n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.centralwidget = QtWidgets.QWidget(parent=Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setMaximumSize(QtCore.QSize(755, 37))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_9.setContentsMargins(10, 6, 10, -1)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.appHeader = QtWidgets.QLabel(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appHeader.sizePolicy().hasHeightForWidth())
        self.appHeader.setSizePolicy(sizePolicy)
        self.appHeader.setMaximumSize(QtCore.QSize(400, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.appHeader.setFont(font)
        self.appHeader.setStyleSheet("font: 87 16pt \"Segoe UI Black\";\n"
"    color: rgb(86, 0, 8);")
        self.appHeader.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.appHeader.setObjectName("appHeader")
        self.verticalLayout_9.addWidget(self.appHeader)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(parent=self.widget_5)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.lineEditTopSeats = QtWidgets.QLineEdit(parent=self.frame_3)
        self.lineEditTopSeats.setText("")
        self.lineEditTopSeats.setObjectName("lineEditTopSeats")
        self.verticalLayout_4.addWidget(self.lineEditTopSeats, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout_3.addWidget(self.frame_3, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_5)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 400))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(parent=self.widget_6)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.textEditTopMovies = QtWidgets.QTextEdit(parent=self.frame_6)
        self.textEditTopMovies.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.textEditTopMovies.setObjectName("textEditTopMovies")
        self.verticalLayout_5.addWidget(self.textEditTopMovies)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(parent=self.widget_6)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.textEditTop3Movies = QtWidgets.QTextEdit(parent=self.frame_5)
        self.textEditTop3Movies.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.textEditTop3Movies.setObjectName("textEditTop3Movies")
        self.verticalLayout_2.addWidget(self.textEditTop3Movies)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.verticalLayout_3.addWidget(self.widget_6, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout.addWidget(self.widget_5)
        self.verticalLayout.addWidget(self.widget_3)
        self.gridLayout.addWidget(self.centralwidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TICKET BOOKING REPORT"))
        self.appHeader.setText(_translate("Dialog", "TICKET BOOKING REPORT"))
        self.label_3.setText(_translate("Dialog", "Top Popular Seats: The most popular seats chosen by customers:"))
        self.label_6.setText(_translate("Dialog", "Top Movies with Most Bookings:"))
        self.textEditTopMovies.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "Top 3 Movies with Most Bookings Since Release:"))
        self.textEditTop3Movies.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
